[project]
name = "flask_app_demo"
version = "0.1.0"
description = "A simple Flask project"
authors = [{name="Your Name", email="you@example.com"}]
dependencies = ["flask>=2.3"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
